version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: micro-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: micro-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySuperSecretKeyForJWTProductionLikeProject12345678901234567890
      SERVER_PORT: 8081
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: micro-payment
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AUTH_SERVICE_URL: http://auth:8081
      SERVER_PORT: 8082
    depends_on:
      - auth
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
