services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - micro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    networks:
      - micro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: micro-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySuperSecretKeyForJWTProductionLikeProject12345678901234567890
      SERVER_PORT: 8081
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - micro-network
    restart: unless-stopped

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: micro-payment
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payment:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AUTH_SERVICE_URL: http://auth:8081
      SERVER_PORT: 8082
    depends_on:
      auth:
        condition: service_started
      postgres-payment:
        condition: service_healthy
    networks:
      - micro-network
    restart: unless-stopped

networks:
  micro-network:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_payment_data: