apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: microservices-demo
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  JWT_SECRET: "mySuperSecretKeyForJWTProductionLikeProject12345678901234567890"
