apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo

resources:
  - namespace.yaml
  - configmap/
  - secrets/
  - postgres-auth/
  - postgres-payment/
  - auth/
  - payment/
  - ingress/
