apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-configmap
  namespace: microservices-demo
data:
  SERVER_PORT: "8082"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  DB_HOST: "postgres-payment-service"
  DB_PORT: "5432"
  DB_NAME: "payment_db"
  AUTH_SERVICE_URL: "http://auth-service.microservices-demo.svc.cluster.local:8081"
