apiVersion: v1
kind: Service
metadata:
  name: postgres-payment-service
  namespace: microservices-demo
  labels:
    app: postgres-payment
spec:
  selector:
    app: postgres-payment
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
