apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-payment
  namespace: microservices-demo
  labels:
    app: postgres-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-payment
  template:
    metadata:
      labels:
        app: postgres-payment
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-payment-configmap
        - secretRef:
            name: postgres-payment-secret
        volumeMounts:
        - name: postgres-payment-storage
          mountPath: /var/lib/postgresql/data
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-payment-storage
        persistentVolumeClaim:
          claimName: postgres-payment-pvc
      - name: init-sql
        configMap:
          name: postgres-payment-init-configmap
