apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-payment-init-configmap
  namespace: microservices-demo
data:
  init.sql: |
    SELECT 'CREATE DATABASE payment_db'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'payment_db');
