apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: microservices-demo
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: demo/payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: payment-configmap
        - secretRef:
            name: payment-secret
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
