apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-service
  namespace: microservices-demo
  labels:
    app: postgres-auth
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
